# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "@anthropic-ai/claude-code-2.0.20" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "2.0.20";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.0.20.tgz";
      sha512 = "VNZa8wQqzoesqFPdj4EAkCgpnvllThfT8Qj+2/8ObHVt0CyNnOG+Y+rkNhQEsQDu5imUj1kf8BSWQqhU/92Xqw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@augmentcode/auggie-0.5.9" = nodeEnv.buildNodePackage {
    name = "_at_augmentcode_slash_auggie";
    packageName = "@augmentcode/auggie";
    version = "0.5.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/@augmentcode/auggie/-/auggie-0.5.9.tgz";
      sha512 = "ItxxFWgEbI/YDO3qB98hP4nc3lFth2XBbLNVrROforGZrQBUG30bXp+waDhf7ahr1tvLelS+UWoIIZpLB8kyiA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Auggie CLI Client by Augment Code";
      homepage = "https://augmentcode.com";
      license = "SEE LICENSE IN LICENSE.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
