# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "@anthropic-ai/claude-code-2.0.5" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "2.0.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.0.5.tgz";
      sha512 = "A7Nnbxf4yvfgnzIbML+IYYkyz4Wmg7McHpqi0pzDmyoz3TUQI1KJc798mlQ0bY7ZeLdrzA0IRCv7yR6bwTa3fA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@augmentcode/auggie-0.5.7" = nodeEnv.buildNodePackage {
    name = "_at_augmentcode_slash_auggie";
    packageName = "@augmentcode/auggie";
    version = "0.5.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/@augmentcode/auggie/-/auggie-0.5.7.tgz";
      sha512 = "hNhrmrF3/AUxJe5OL2M8BluyN+KD/Rc2rTJF6NrKAF7fqcQNsIbBICbz5b2+DMb02STFJup6dgkVF0HLhW34Bw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Auggie CLI Client by Augment Code";
      homepage = "https://augmentcode.com";
      license = "SEE LICENSE IN LICENSE.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
